# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - automerged_updates:
      - match:
          dependency_type: "development"
    commit_message:
      include_scope: true
      prefix: "Build"
    default_labels:
      - "dependency"
    directory: "/"
    ignored_updates:
      - match:
          dependency_name: "doctrine/annotations"
      - match:
          dependency_name: "doctrine/collections"
      - match:
          dependency_name: "doctrine/orm"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
